name: doanltddfinal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_storage: any
  firebase_messaging: any
  flutter_local_notifications: ^17.2.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  file_picker: ^8.1.5
  image_picker: ^1.2.2
  fl_chart: ^1.2.0
  cloudinary_public: ^0.23.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
