// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKsONESLKC9pFPeL82lPTolBXaxZ6JmVM',
    appId: '1:786323330998:web:5611cc114768f1b360d317',
    messagingSenderId: '786323330998',
    projectId: 'fir-fd3b4',
    authDomain: 'fir-fd3b4.firebaseapp.com',
    databaseURL: 'https://fir-fd3b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fd3b4.firebasestorage.app',
    measurementId: 'G-JJP5NMXK97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1X-jHfUThM7Q3_shBm0knAOoiv0kgDFM',
    appId: '1:786323330998:android:490bdd566de7a61960d317',
    messagingSenderId: '786323330998',
    projectId: 'fir-fd3b4',
    databaseURL: 'https://fir-fd3b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fd3b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPTRJdI7pcmo-d6WL650uQ-k4-l5Iv5wQ',
    appId: '1:786323330998:ios:985edec49837765960d317',
    messagingSenderId: '786323330998',
    projectId: 'fir-fd3b4',
    databaseURL: 'https://fir-fd3b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fd3b4.firebasestorage.app',
    iosBundleId: 'com.example.doanltddfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPTRJdI7pcmo-d6WL650uQ-k4-l5Iv5wQ',
    appId: '1:786323330998:ios:985edec49837765960d317',
    messagingSenderId: '786323330998',
    projectId: 'fir-fd3b4',
    databaseURL: 'https://fir-fd3b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fd3b4.firebasestorage.app',
    iosBundleId: 'com.example.doanltddfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKsONESLKC9pFPeL82lPTolBXaxZ6JmVM',
    appId: '1:786323330998:web:70dd2cee4a04843260d317',
    messagingSenderId: '786323330998',
    projectId: 'fir-fd3b4',
    authDomain: 'fir-fd3b4.firebaseapp.com',
    databaseURL: 'https://fir-fd3b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fd3b4.firebasestorage.app',
    measurementId: 'G-6TQ1L1L8LV',
  );
}
